# Generated by Django 2.2.8 on 2020-01-14 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please use a valid phone number', regex='^0\\d{10}$')])),
                ('company', models.CharField(max_length=35)),
                ('address_first_line', models.CharField(max_length=35)),
                ('town', models.CharField(default='Plymouth', max_length=20)),
                ('post_code', models.CharField(max_length=9)),
                ('country', models.CharField(default='Great Britain', max_length=20)),
                ('sort_code', models.IntegerField(max_length=6)),
                ('account_no', models.IntegerField(max_length=8)),
                ('iban', models.CharField(max_length=34)),
                ('card_no', models.IntegerField(max_length=16)),
                ('card_exp_date', models.DateField()),
                ('obs', models.TextField()),
            ],
        ),
    ]
