# Generated by Django 2.2.8 on 2020-01-14 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_no',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid account number', regex='^\\d{7, 8}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card_no',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid card number', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sort_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid sort code', regex='^\\d{6}$')]),
        ),
    ]
