# Generated by Django 2.2.9 on 2020-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
