# Generated by Django 2.2.9 on 2020-04-03 15:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_auto_20200204_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid IBAN. Must be between 15 and 32 characters. Please use CAPITAL LETTERS.', regex='^[0-9A-Z]{15,32}$')]),
        ),
    ]
