# Generated by Django 2.2.8 on 2020-01-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200114_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='obs',
            field=models.TextField(blank=True),
        ),
    ]
