# Generated by Django 2.2.8 on 2020-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200114_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
