# Generated by Django 2.2.8 on 2020-01-14 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20200114_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_no',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid account number. If the account number has less than 8 digits, please add 0(zero) in front.', regex='^\\d{8}$')]),
        ),
    ]
