# Generated by Django 2.2.8 on 2020-01-14 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20200114_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(code='nomatch', message='Invalid IBAN. Please use CAPITAL LETTERS.', regex='^[0-9A-Z]{15,32}$')]),
        ),
    ]
