# Generated by Django 2.2.8 on 2020-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20200114_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='obs',
            new_name='notes',
        ),
    ]
