# Generated by Django 2.2.9 on 2020-01-19 18:45

from django.db import migrations, models
import django.db.models.deletion
import subscriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_renewal', models.DateField(blank=True, default=subscriptions.models.date_renewal_default, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('password', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passwords.Password')),
            ],
        ),
    ]
