# Generated by Django 2.2.9 on 2020-02-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='username',
        ),
    ]
