# Generated by Django 2.2.9 on 2020-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='website',
            field=models.CharField(choices=[('123reg', '123Reg'), ('Heroku', 'Heroku'), ('GitHub', 'GitHub'), ('DigitalOcean', 'DigitalOcean')], default='GitHub', max_length=25),
        ),
    ]
