# Generated by Django 2.2.9 on 2020-02-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200201_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.Website'),
        ),
    ]
