# Generated by Django 2.2.9 on 2020-04-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20200403_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notify_by_email',
            field=models.BooleanField(default=True),
        ),
    ]
