# Generated by Django 2.2.9 on 2020-01-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passwords', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_github', models.URLField()),
                ('url_heroku', models.URLField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('password', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passwords.Password')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
