# Generated by Django 2.2.9 on 2020-01-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url_heroku',
            field=models.URLField(blank=True, null=True),
        ),
    ]
