# Generated by Django 2.2.9 on 2020-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='website',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='website',
            name='password_digitalocean',
        ),
        migrations.RemoveField(
            model_name='website',
            name='password_github',
        ),
        migrations.RemoveField(
            model_name='website',
            name='password_heroku',
        ),
        migrations.RemoveField(
            model_name='website',
            name='password_other',
        ),
        migrations.RemoveField(
            model_name='website',
            name='project',
        ),
        migrations.RemoveField(
            model_name='website',
            name='url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='url_digitalocean',
        ),
        migrations.RemoveField(
            model_name='website',
            name='url_github',
        ),
        migrations.RemoveField(
            model_name='website',
            name='url_heroku',
        ),
        migrations.RemoveField(
            model_name='website',
            name='url_other',
        ),
        migrations.RemoveField(
            model_name='website',
            name='username',
        ),
        migrations.RemoveField(
            model_name='website',
            name='username_digitalocean',
        ),
        migrations.RemoveField(
            model_name='website',
            name='username_github',
        ),
        migrations.RemoveField(
            model_name='website',
            name='username_heroku',
        ),
        migrations.RemoveField(
            model_name='website',
            name='username_other',
        ),
        migrations.AddField(
            model_name='website',
            name='link',
            field=models.URLField(default='www.heroku.com', unique=True),
        ),
        migrations.AddField(
            model_name='website',
            name='name',
            field=models.CharField(default='Heroku', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='website',
            name='subscription',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='password',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
