# Generated by Django 2.2.9 on 2020-02-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='for_password',
        ),
        migrations.RemoveField(
            model_name='website',
            name='for_subscription',
        ),
    ]
