# Generated by Django 2.2.9 on 2020-02-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20200203_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='link',
            new_name='url',
        ),
    ]
