# Generated by Django 2.2.9 on 2020-02-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('url_github', models.URLField(blank=True, null=True)),
                ('username_github', models.CharField(blank=True, max_length=25, null=True)),
                ('password_github', models.CharField(blank=True, max_length=50, null=True)),
                ('url_heroku', models.URLField(blank=True, null=True)),
                ('username_heroku', models.CharField(blank=True, max_length=25, null=True)),
                ('password_heroku', models.CharField(blank=True, max_length=50, null=True)),
                ('url_digitalocean', models.URLField(blank=True, null=True)),
                ('username_digitalocean', models.CharField(blank=True, max_length=25, null=True)),
                ('password_digitalocean', models.CharField(blank=True, max_length=50, null=True)),
                ('url_other', models.URLField(blank=True, null=True)),
                ('username_other', models.CharField(blank=True, max_length=25, null=True)),
                ('password_other', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'ordering': ['project', 'url', 'url_github', 'url_heroku'],
            },
        ),
    ]
